name: create-draft

on:
  workflow_dispatch:
    inputs:
      version:
        description: Specify plugin version
        default: 1.0.0.1
        required: true

jobs:
  create-draft-release:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Create draft release
      id: create-release
      uses: ncipollo/release-action@v1
      with:
        allowUpdates: true
        draft: true
        prerelease: false
        body: "Create draft"
        tag: v${{ github.event.inputs.version }}
        name: Draft release v${{ github.event.inputs.version }}
        token: ${{ secrets.GITHUB_TOKEN }}
