name: publish-latest

on:
  workflow_dispatch:
    inputs:
      version:
        description: Specify tag_name or release_id of draft release
        default: 1.0.0.1
        required: true

jobs:
  build-and-release-production-installer:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Publish draft release
      uses: ncipollo/release-action@v1
      with:
        allowUpdates: true
        tag: v${{ github.event.inputs.version }}
        name: Release v${{ github.event.inputs.version }}
        body: "Create production installer ${{ github.event.inputs.version }}"
        token: ${{ secrets.GITHUB_TOKEN }}
